language: java
jdk:
  - oraclejdk8
before_install:
  - sudo apt-get update
  - echo "Let's start Maven Package!"
script:
  - mvn test
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - docker-compose build
before_deploy:
  echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
deploy:
  provider: script
  script:
    docker tag docker-to-aws-with-java:latest marcoar1978/docker-to-aws-with-java:latest;
    docker push marcoar1978/docker-to-aws-with-java;
  on:
    branch: master
notifications:
  email: false